# ????????????????????
rootLogger.level = info
rootLogger.appenderRefs = Console, FileAppender
rootLogger.appenderRef.Console.ref = Console
rootLogger.appenderRef.FileAppender.ref = FileAppender

# ???????
appender.console.type = Console
appender.console.name = Console
appender.console.target = SYSTEM_OUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss.SSS} [%t] %-5level %logger{36} : %msg%n

# ??????
appender.file.type = File
appender.file.name = FileAppender
appender.file.fileName = D:/images/automation/logs/app.txt
appender.file.append = true
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} : %msg%n
