server:
  port: 8090
  servlet:
    context-path: /

spring:
  application:
    name: ReDemo
  session:
    store-type: redis
    timeout: 60s
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    username: edms
    password: edms
    url: jdbc:mysql://localhost:3306/newbee_mall_db?useUnicode=true&amp&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置XML映射文件中指定的实体类别名路径
  type-aliases-package: com.marks.redemo.entity
  configuration:
    #springboot开启mybatis驼峰命名匹配映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


