server:
  port: 8070
  servlet:
    context-path: /kk

spring:
    application:
      name: kk-platform-game-auto
    profiles:
      active: dev
    web:
      resources:
        static-locations: classpath:/static/, classpath:/templates/
    # 数据库配置
    datasource:
      url: jdbc:mysql://localhost:3306/image_3D?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: HikariPool-kkplatform
        maximum-pool-size: 20
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
        auto-commit: true

# 日志
logging:
  level:
    root: INFO
    com.marks.kkPlatformGameAuto: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    path: logs/
    name: ${LOG_PATH:logs}/${spring.application.name}.log

spring.config.import:
  - classpath:game-common.yml